<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIFg5Gxr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIFg5Gxr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIFg5Gxr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIFg5Gxr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIFg5Gxr\App_KernelDevDebugContainer([
    'container.build_hash' => 'IFg5Gxr',
    'container.build_id' => 'da96eac9',
    'container.build_time' => 1738850294,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIFg5Gxr');
